source "https://rubygems.org"

gem "net-smtp", "~> 0.5"
gem "pony",     "~> 1.13"
gem "ostruct",  "~> 0.6"
gem "puma",     "~> 6.4"
gem "rackup",   "~> 2.2"
gem "sinatra",  "~> 4.1"

gem "opentelemetry-sdk",                     "~> 1.4"
gem "opentelemetry-exporter-otlp",           "~> 0.29"
gem "opentelemetry-instrumentation-sinatra", "~> 0.24"
